# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

# dependency for rjags
apt_packages:
  - jags
  
# install linux binary package versions to avoid travis too long log error
r_binary_packages:
  - rjags
  - rstan
  - rstanarm
  - MCMCpack
  - openssl
  - BH
  - igraph

# set up vars for Stan
before_install:
  # from https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -march=native -mtune=native -fPIC" >> ~/.R/Makevars
  - echo "CXX14=g++" >> ~/.R/Makevars

r_packages:
    - covr
    - pkgdown

after_success:
    - Rscript -e 'covr::codecov()'
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  on:
    branch: master
    
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://ShanaScogin:$GITHUB_API_KEY@github.com/ShanaScogin/BayesPostEst-gh-pages gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
