# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: FALSE
sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
cache: packages

os:
- linux
- osx




