# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: FALSE
sudo: true

before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  
install: 
  - R -e "install.packages('rstan')"

script: 
  - R -e "rstan::stan_version()"
  
cache: packages

os:
- linux
- osx

after_success:
    - Rscript -e 'covr::codecov()'







