# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: FALSE
sudo: TRUE

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install: 
  - R -e "install.packages('rstan')"

script: 
  - R -e "rstan::stan_version()"
  
cache: packages

os:
- linux
- osx









