#'This function generates ROC and precision-recall curves 
#'after fitting a logit/probit regression model in Stan
#'references: Area under the curve functions written by Andreas Beger
#'<https://ssrn.com/abstract=2765419>
#'
#'@title ROC and Precision-recall Curve
#'@description This function generates ROC and precision-recall curves 
#'after fitting a logit/probit regression model in Stan
#'references: Area under the curve functions written by Andreas Beger
#'<https://ssrn.com/abstract=2765419>
#'@param sims MCMC object generated by R2jags, rjags, R2WinBUGS, R2OpenBUGS, 
#'MCMCpack, rstan, rstanarm
#'@param modelframe model frame used to fit the model
#'@return A list with four elements: 
#'area_under_roc: area under ROC curve (scalar)
#'area_under_prc: area under precision-recall curve (scalar)
#'prc_dat: data to plot precision-recall curve (data frame)
#'roc_dat: data to plot ROC curve (data frame)
#'@examples
#' \donttest{
#'   set.seed(123456)
#' }
#'@export

mcmcRocPrc <- function(sims, # this needs to be generalized
                       modelframe){
  
  # Prepare MCMC output
  if (class(sims) == "stanreg"){
  pred_prob <- rstanarm::posterior_linpred(sims, transform = TRUE)
  }

  RocPrcOneDraw <- function(pred_prob_vector){
    # run this function over each row (iteration) of the pred_prob matrix

  # y_pred <- apply(X = pred_prob, MARGIN = 2, FUN = function(x) median(x))

  # Observed y and x
  pred_obs <- data.frame(y_pred = pred_prob_vector, y_obs = modelframe[, 1])						 

  # For more on the area under the curve functions see Andreas Beger
  # <https://ssrn.com/abstract=2765419>
  
  auc_roc <- function(obs, pred) {
    pred <- ROCR::prediction(pred, obs)
    auc  <- ROCR::performance(pred, "auc")@y.values[[1]]
    return(auc)
  }
  
  auc_pr <- function(obs, pred) {
    xx.df <- ROCR::prediction(pred, obs)
    perf  <- ROCR::performance(xx.df, "prec", "rec")
    xy    <- data.frame(recall = perf@x.values[[1]], 
                        precision = perf@y.values[[1]])
    
    # take out division by 0 for lowest threshold
    xy <- subset(xy, !is.nan(xy$precision))
    
    res   <- caTools::trapz(xy$recall, xy$precision)
    res
  }
  
  area_under_roc <- auc_roc(obs = pred_obs$y_obs, pred = pred_obs$y_pred)
  
  area_under_prc <- auc_pr(obs = pred_obs$y_obs, pred = pred_obs$y_pred)
  
  prediction_obj <- ROCR::prediction(predictions = pred_obs$y_pred,
                               labels = pred_obs$y_obs)
  
  prc_performance_obj <- ROCR::performance(prediction.obj = prediction_obj,
                                     measure = "prec",
                                     x.measure = "rec")
  
  prc_dat <- data.frame(x = prc_performance_obj@x.values,
                        y = prc_performance_obj@y.values)
  names(prc_dat) <- c("x", "y")
  
  roc_performance_obj <- ROCR::performance(prediction.obj = prediction_obj,
                                     measure = "tpr",
                                     x.measure = "fpr")
  
  roc_dat <- data.frame(x = roc_performance_obj@x.values,
                        y = roc_performance_obj@y.values)
  names(roc_dat) <- c("x", "y")
  
  # Results as a list
  one_result <- list()
  one_result$area_under_roc <- area_under_roc
  one_result$area_under_prc <- area_under_prc
  one_result$prc_dat <- prc_dat
  one_result$roc_dat <- roc_dat

  return(one_result)
}

all_results <- list()
for(i in 1:nrow(pred_prob)){
  all_results[[i]] <- RocPrcOneDraw(pred_prob[i, ])
}
  
  return(all_results)
}